services:
  web:
    image: scrapbookimage:latest
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - scrapbook_net
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_USER=db
      - DB_PASSWORD=3Uy@7SGMAHVyC^Oo
      - DB_NAME=db
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    restart: always
    networks:
      - scrapbook_net
    volumes:
      - redis_data:/data

  db:
    image: mariadb:11.6.2
    restart: always
    volumes:
      - db_config:/config
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=3Uy@7SGMAHVyC^Oo
      - MYSQL_ROOT_PASSWORD=3Uy@7SGMAHVyC^Oo
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "db", "-p3Uy@7SGMAHVyC^Oo"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      scrapbook_net:
        aliases:
          - db
          - mariadb
          - mysql

networks:
  scrapbook_net:
    driver: bridge

volumes:
  app_data:
  db:
  db_config:
  redis_data: