version: '3.8'

services:
  web:
    build:
      context: https://github.com/isaaclee0/scrapbook.git
      dockerfile: Dockerfile
    image: scrapbook:prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app
    networks:
      - npm_proxy
      - scrapbook_net
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - scrapbook_net
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:11.6.2
    restart: unless-stopped
    volumes:
      - db_config:/config
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=256M
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "db", "-p${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      scrapbook_net:
        aliases:
          - db
          - mariadb
          - mysql

networks:
  npm_proxy:
    external: true
  scrapbook_net:
    driver: bridge

volumes:
  app_data:
    driver: local
  db:
    driver: local
  db_config:
    driver: local
  redis_data:
    driver: local 