services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    networks:
      - scrapbook_net
    environment:
      - FLASK_ENV=development  # Changed to development for instant changes
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_USER=db
      - DB_PASSWORD=${DB_PASSWORD:-your_secure_password_here}
      - DB_NAME=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BREVO_API_KEY=${BREVO_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - MAGIC_LINK_EXPIRY=${MAGIC_LINK_EXPIRY:-1800}
      - SESSION_EXPIRY=${SESSION_EXPIRY:-2592000}
      - DEFAULT_USER_EMAIL=${DEFAULT_USER_EMAIL:-admin@localhost}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - scrapbook_net
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mariadb:11.6.2
    restart: unless-stopped
    volumes:
      - db_config:/config
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-your_secure_password_here}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-your_secure_root_password_here}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=256M
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "db", "-p${MYSQL_PASSWORD:-your_secure_password_here}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      scrapbook_net:
        aliases:
          - db
          - mariadb
          - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=db
      - PMA_PASSWORD=${MYSQL_PASSWORD:-your_secure_password_here}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-your_secure_root_password_here}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - scrapbook_net

networks:
  scrapbook_net:
    driver: bridge

volumes:
  db:
    driver: local
  db_config:
    driver: local
  redis_data:
    driver: local 